/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;


/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.AddLookupTableType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AddLookupTableTypeValidator
{
	boolean validate();

	boolean validateConstraintName(String value);
	boolean validateExistingColumnName(String value);
	boolean validateExistingTableCatalogName(String value);
	boolean validateExistingTableName(String value);
	boolean validateExistingTableSchemaName(String value);
	boolean validateNewColumnDataType(String value);
	boolean validateNewColumnName(String value);
	boolean validateNewTableCatalogName(String value);
	boolean validateNewTableName(String value);
	boolean validateNewTableSchemaName(String value);
}
