/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.AlterSequenceType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AlterSequenceTypeValidator
{
	boolean validate();

	boolean validateCacheSize(BigInteger value);
	boolean validateCatalogName(String value);
	boolean validateCycle(Object value);
	boolean validateIncrementBy(String value);
	boolean validateMaxValue(String value);
	boolean validateMinValue(String value);
	boolean validateOrdered(Object value);
	boolean validateSchemaName(String value);
	boolean validateSequenceName(String value);
	boolean validateStartValue(String value);
}
