/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;


/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.ColumnType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ColumnTypeValidator
{
	boolean validate();

	boolean validateDefaultValue(String value);
	boolean validateDefaultValueBoolean(Object value);
	boolean validateDefaultValueComputed(String value);
	boolean validateDefaultValueDate(String value);
	boolean validateDefaultValueNumeric(String value);
	boolean validateHeader(String value);
	boolean validateIndex(Object value);
	boolean validateName(String value);
	boolean validateType(String value);
}
