/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;


/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.ConstraintsType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintsTypeValidator
{
	boolean validate();

	boolean validateCheckConstraint(String value);
	boolean validateDeferrable(Object value);
	boolean validateDeleteCascade(Object value);
	boolean validateForeignKeyName(String value);
	boolean validateInitiallyDeferred(Object value);
	boolean validateNullable(Object value);
	boolean validatePrimaryKey(Object value);
	boolean validatePrimaryKeyName(String value);
	boolean validatePrimaryKeyTablespace(String value);
	boolean validateReferencedColumnNames(String value);
	boolean validateReferencedTableCatalogName(String value);
	boolean validateReferencedTableName(String value);
	boolean validateReferencedTableSchemaName(String value);
	boolean validateReferences(String value);
	boolean validateUnique(Object value);
	boolean validateUniqueConstraintName(String value);
}
