/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.liquibase.xml.ns.dbchangelog.WhereParamsType;

/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.DeleteType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeleteTypeValidator
{
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateWhere(EObject value);
	boolean validateWhereParams(WhereParamsType value);
	boolean validateCatalogName(String value);
	boolean validateSchemaName(String value);
	boolean validateTableName(String value);
}
