/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;

import org.eclipse.emf.common.util.EList;

import org.liquibase.xml.ns.dbchangelog.ArgType;

/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.ExecuteCommandType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExecuteCommandTypeValidator
{
	boolean validate();

	boolean validateArg(EList<ArgType> value);
	boolean validateExecutable(String value);
	boolean validateOs(String value);
}
