/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.IncludeAllType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IncludeAllTypeValidator
{
	boolean validate();

	boolean validateContext(String value);
	boolean validateErrorIfMissingOrEmpty(Object value);
	boolean validateFilter(String value);
	boolean validatePath(String value);
	boolean validateRelativeToChangelogFile(Object value);
	boolean validateResourceComparator(String value);
	boolean validateAnyAttribute(FeatureMap value);
}
