/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;

import org.eclipse.emf.common.util.EList;

import org.liquibase.xml.ns.dbchangelog.ColumnType2;

/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.InsertType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InsertTypeValidator
{
	boolean validate();

	boolean validateColumn(EList<ColumnType2> value);
	boolean validateCatalogName(String value);
	boolean validateDbms(String value);
	boolean validateSchemaName(String value);
	boolean validateTableName(String value);
}
