/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.liquibase.xml.ns.dbchangelog.ColumnType1;

/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.LoadUpdateDataType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoadUpdateDataTypeValidator
{
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateColumn(EList<ColumnType1> value);
	boolean validateCatalogName(String value);
	boolean validateEncoding(String value);
	boolean validateFile(String value);
	boolean validateOnlyUpdate(boolean value);
	boolean validatePrimaryKey(String value);
	boolean validateQuotchar(String value);
	boolean validateRelativeToChangelogFile(Object value);
	boolean validateSchemaName(String value);
	boolean validateSeparator(String value);
	boolean validateTableName(String value);
}
