/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.liquibase.xml.ns.dbchangelog.AppendType;
import org.liquibase.xml.ns.dbchangelog.PrependType;
import org.liquibase.xml.ns.dbchangelog.RegExpReplaceType;
import org.liquibase.xml.ns.dbchangelog.ReplaceType;

/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.ModifySqlType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModifySqlTypeValidator
{
	boolean validate();

	boolean validateModifySqlChildren(FeatureMap value);
	boolean validateReplace(EList<ReplaceType> value);
	boolean validateRegExpReplace(EList<RegExpReplaceType> value);
	boolean validatePrepend(EList<PrependType> value);
	boolean validateAppend(EList<AppendType> value);
	boolean validateApplyToRollback(Object value);
	boolean validateContext(String value);
	boolean validateDbms(String value);
	boolean validateLabels(String value);
}
