/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;


/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.ParamType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParamType1Validator
{
	boolean validate();

	boolean validateName(String value);
	boolean validateValue(String value);
	boolean validateValueBoolean(String value);
	boolean validateValueComputed(String value);
	boolean validateValueDate(String value);
	boolean validateValueNumeric(String value);
	boolean validateValueSequenceCurrent(String value);
	boolean validateValueSequenceNext(String value);
}
