/**
 *
 * $Id$
 */
package org.liquibase.xml.ns.dbchangelog.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.liquibase.xml.ns.dbchangelog.ColumnType2;
import org.liquibase.xml.ns.dbchangelog.WhereParamsType;

/**
 * A sample validator interface for {@link org.liquibase.xml.ns.dbchangelog.UpdateType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UpdateTypeValidator
{
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateColumn(EList<ColumnType2> value);
	boolean validateWhere(EObject value);
	boolean validateWhereParams(WhereParamsType value);
	boolean validateCatalogName(String value);
	boolean validateSchemaName(String value);
	boolean validateTableName(String value);
}
